version: "2.4"
services:

  nginx:
    image: pablolibo/whoami:latest
    ports:
     - 80:8000

  watchtower:
    image: containrrr/watchtower
    command: --interval 10
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock" 
